# Generated by Django 5.2.8 on 2025-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("hero", "Section Hero"),
                            ("features", "Nos forces"),
                            ("products_intro", "Intro Produits"),
                            ("gallery", "Galerie"),
                            ("cta", "Appel à l'action"),
                            ("about", "À propos"),
                            ("services_intro", "Intro Services"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="content/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contenu de page",
                "verbose_name_plural": "Contenus de page",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "name_en",
                    models.CharField(
                        blank=True, help_text="Nom en anglais", max_length=255
                    ),
                ),
                ("description", models.TextField()),
                (
                    "features",
                    models.TextField(help_text="Caractéristiques (une par ligne)"),
                ),
                ("image", models.ImageField(upload_to="products/")),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "icon",
                    models.CharField(
                        default="⭐", help_text="Emoji ou symbole", max_length=50
                    ),
                ),
                ("description", models.TextField()),
                (
                    "features",
                    models.TextField(help_text="Caractéristiques (une par ligne)"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
            },
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
