# Generated by Django 5.2.8 on 2025-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_pagecontent_product_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
