# Generated by Django 5.2.8 on 2025-11-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_service_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="icon",
        ),
    ]
